version: '3.9'
services:
# Client apps 
  chat-app-react:
    build:
      context: ./chat-app-react
      dockerfile: Dockerfile
    ports:
      - 80:80
  alerting-app-react:
    build:
      context: ./alerting-app-react
      dockerfile: Dockerfile
    ports:
      - 81:80 
  app-shell-react:
    build:
      context: ./app-shell-react
      dockerfile: Dockerfile
    ports:
      - 82:80                
# backend services           
  chat-service:
    build: 
      context: ./chat-service
      dockerfile: Dockerfile.jvm-multi 
    environment: 
      - QUARKUS_HTTP_CORS=true
    ports:
        - 8080:8080
  alerting-service:
    build: 
      context: ./alerting-service
      dockerfile: Dockerfile.jvm-multi 
    environment: 
      - QUARKUS_HTTP_CORS=true
    ports:
        - 8081:8080
  app-service:
    build: 
      context: ./app-service
      dockerfile: Dockerfile.jvm-multi 
    environment: 
      - QUARKUS_HTTP_CORS=true
    ports:
        - 8082:8080                     